# Alertmanager configuration for Kubernetes deployment

# Image configuration
image:
  repository: prom/alertmanager
  tag: v0.28.0
  pullPolicy: IfNotPresent

# Resource configuration
#resources:
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

# Service configuration
service:
  type: ClusterIP
  port: 9093
  annotations: {}

# Persistence configuration
persistence:
  enabled: true
  size: 1Gi
  # Use default storage class
  # storageClass: ""

# Alertmanager configuration
config:
  global:
    resolve_timeout: 5m
    smtp_smarthost: 'smtp.example.com:587'
    smtp_from: 'alertmanager@example.com'
    smtp_auth_username: 'alertmanager'
    smtp_auth_password: 'password'
    smtp_require_tls: true

  route:
    group_by: ['alertname', 'job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'default-receiver'
    routes:
      - match:
          severity: critical
        receiver: 'critical-receiver'
      - match:
          severity: warning
        receiver: 'warning-receiver'
    
  receivers:
    - name: 'default-receiver'
      email_configs:
        - to: 'team@example.com'
          send_resolved: true

    - name: 'warning-receiver'
      email_configs:
        - to: 'alerts@example.com'
          send_resolved: true

    - name: 'critical-receiver'
      email_configs:
        - to: 'oncall@example.com'
          send_resolved: true
        
    - name: 'blackhole'
      # Empty receiver for alerts that should be silently dropped

  inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'instance']

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9093"

# Security context
securityContext:
  runAsUser: 65534
  runAsNonRoot: true

# Readiness probe
readinessProbe:
  httpGet:
    path: /-/ready
    port: 9093
  initialDelaySeconds: 30
  timeoutSeconds: 30

# Liveness probe
livenessProbe:
  httpGet:
    path: /-/healthy
    port: 9093
  initialDelaySeconds: 30
  timeoutSeconds: 30
