server:
  datasource:
    url: http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local:8428
  
  remoteWrite:
    url: http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write
  
  remoteRead:
    url: http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/read
  
  evaluationInterval: 30s
  
  externalLabels:
    cluster: production
    environment: kubernetes

  notifier:
    alertmanager:
      url: "http://alertmanager.observability.svc.cluster.local:9093"

  config:
    alerts:
      groups:

        - name: "K8s Alerts"
          rules:

          - alert: UselessBoxImagePullBackOff
            expr: kube_pod_container_status_waiting_reason{reason="ImagePullBackOff", container="useless-box"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Falha ao puxar imagem no namespace {{ $labels.namespace }}"
              description: "O container useless-box em {{ $labels.namespace }} está com erro de ImagePullBackOff."

          - alert: UselessBoxPodUnschedulable
            expr: kube_pod_status_unschedulable{namespace="ns-52327214"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod não agendado no namespace {{ $labels.namespace }}"
              description: "A aplicação useless-box está com requests/limits impossíveis de atender."

          - alert: RedisPVCMissing
            expr: kube_persistentvolumeclaim_status_phase{phase="Lost", namespace="ns-52327214"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "PVC perdido no namespace {{ $labels.namespace }}"
              description: "O Redis perdeu seu PVC e não poderá iniciar corretamente."

          - alert: UselessBoxAffinityUnmatch
            expr: kube_pod_status_unschedulable{namespace="ns-52327214"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Affinity inviável no namespace {{ $labels.namespace }}"
              description: "A aplicação useless-box está com um nodeAffinity impossível de atender."

          - alert: ResourceQuotaExceeded
            expr: |
              kube_resourcequota{type="used"} > on (resource, namespace) kube_resourcequota{type="hard"}
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "ResourceQuota excedida no namespace {{ $labels.namespace }}"
              description: "O recurso {{ $labels.resource }} excedeu o limite definido pela quota no namespace {{ $labels.namespace }}."

          - alert: NodeNotReady
            expr: kube_node_status_condition{condition="Ready", status="false"} == 1
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Node {{ $labels.node }} não está pronto"
              description: "O node {{ $labels.node }} está marcado como NotReady há mais de 2 minutos."

          - alert: PodEvictedOOM
            expr: kube_pod_status_reason{reason="Evicted"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod evicted por pressão de memória"
              description: "O pod {{ $labels.pod }} foi evicted no namespace {{ $labels.namespace }} por falta de recursos (memória provavelmente)."

resources:
  limits:
    cpu: 500m
    memory: 511mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  enabled: true
  servicePort: 8880
  targetPort: 8880
  type: ClusterIP
  
serviceMonitor:
  enabled: false